"""
AI-Generated Contracts
This folder contains smart contracts generated by the AI engine.

WARNING: Always audit AI-generated contracts before deployment to MainNet.
These contracts are for educational and testing purposes.
"""

from pathlib import Path

CONTRACTS_DIR = Path(__file__).parent

def list_generated_contracts():
    """List all AI-generated contract files."""
    return [f for f in CONTRACTS_DIR.glob("contract_*.py")]

def get_latest_contract():
    """Get the most recently generated contract."""
    contracts = list_generated_contracts()
    if not contracts:
        return None
    return max(contracts, key=lambda f: f.stat().st_mtime)
